[package]
name = "blaze-runtime"
edition = "2024"

[dependencies]
chrono = { workspace = true }
serde = {workspace= true}
serde_json = { workspace = true }
log = { workspace = true }
dirs = { workspace = true}
tempfile = { workspace = true } 
serial_test = { workspace = true}
